### ISSUE TITLE
Improve preparation time

### ISSUE THREAD

**Issue by easbar** [easbar/fast_paths#33]
Some of the ideas taken from this discussion: https://github.com/Stunkymonkey/osm_ch/issues/1

* [x] cancel witness searches after a certain amount of nodes have been explored -> see #37 
* [ ] use contracted_neighbors heuristic
* [ ] use flat array for preparation graph
* [ ] parallelization https://github.com/Stunkymonkey/osm_ch/issues/1#issuecomment-877780244
* [ ] contract only a certain fraction of nodes
* [x] find out why abstreet graph preparation is slow compared to e.g. plain OSM maps https://github.com/Stunkymonkey/osm_ch/issues/1#issuecomment-876583423 -> see #37
* [ ] clean up query code? https://github.com/Stunkymonkey/osm_ch/issues/1#issuecomment-877780244
